FROM mcr.microsoft.com/devcontainers/typescript-node:22
RUN yarn global add typescript ts-node nodemon
RUN yarn global add http-server
RUN wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.3.9_amd64.deb && sudo apt install ./mongodb-mongosh_2.3.9_amd64.deb